# ID of the survey is the filename (without extension)

# Title and description to show
title: A Quick Survey
description: |
  A longer description

# Dictionary of options
# Keys are unique IDs that will be saved on response
options:
  opt_1:
    # The short code for an emoji
    icon: smile_cat # = 😺
    name: The name of the option
    # One of default | red | yellow
    color: default

# Conditions for showing the survey to a user
# This is evaluated each time the user sends a message
trigger:
  # Random probability of showing, given all other conditions are met
  # If multiple surveys meet the conditions, their probabilities are normalized
  # and selected randomly based on those normalized scores.
  with_probability: 0.8
  # Show when this user visits for the first time
  first_time_user: true

  # Show after the user has sent at least five messages in the currenct session
  only_after_n_messages: 3
